# Project: Magneta Languange
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o module.o module_utility.o magenta_lex.o magenta_.o
LINKOBJ  = main.o module.o module_utility.o magenta_lex.o magenta_.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Magenta Languange.exe"
CXXFLAGS = $(CXXINCS) -g3 -std=c++11 -std=gnu++11
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

module.o: module.cpp
	$(CPP) -c module.cpp -o module.o $(CXXFLAGS)

module_utility.o: module_utility.cpp
	$(CPP) -c module_utility.cpp -o module_utility.o $(CXXFLAGS)

magenta_lex.o: magenta_lex.cpp
	$(CPP) -c magenta_lex.cpp -o magenta_lex.o $(CXXFLAGS)

magenta_.o: magenta_.cpp
	$(CPP) -c magenta_.cpp -o magenta_.o $(CXXFLAGS)
